# Generated by Django 5.2.1 on 2025-05-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="modelo",
            fields=[
                (
                    "Id_user",
                    models.CharField(
                        auto_created=True,
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fristName", models.CharField(max_length=50)),
                ("lastName", models.CharField(max_length=50)),
                ("yearOld", models.IntegerField(max_length=3)),
            ],
        ),
    ]
