# Generated by Django 5.2.1 on 2025-05-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelos", "0002_musician_album"),
    ]

    operations = [
        migrations.CreateModel(
            name="person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                (
                    "shirt_size",
                    models.CharField(
                        choices=[("S", "small"), ("M", "medium"), ("L", "large")],
                        max_length=1,
                    ),
                ),
            ],
        ),
    ]
