# Generated by Django 5.2.1 on 2025-05-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelos", "0004_runner"),
    ]

    operations = [
        migrations.CreateModel(
            name="fruit",
            fields=[
                (
                    "name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
