# Generated by Django 5.2.1 on 2025-05-30 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelos", "0005_fruit"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomatiPK",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "firstName",
                    models.CharField(max_length=30, verbose_name="person´s first name"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ForeignKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seconMane", models.CharField(max_length=20)),
                (
                    "fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modelos.automatipk",
                    ),
                ),
            ],
        ),
    ]
